name: terraform

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
          unzip terraform_1.7.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Check File Format
        id: fmt
        run: terraform fmt

      - name: Initialize terraform
        id: init
        run: terraform init

      - name: Validate code
        id: validate
        run: terraform validate
